In [1]:
import glob
import pandas as pd
import numpy as np
import regex as re
import missingno as msno
        
def path_to_dict(path):
    '''
    Takes a file path in as input and return a dictionary of dataframes
    where the filename without the .csv is the key for the corresponding 
    dataframe.
    '''
    files = glob.glob(path + "*.csv")
    path = re.sub('\W+', " ", path)
    dataframe_collection = {} 
    for file in files:
        key = re.sub('\W+', " ", file)
        key = key.replace(path,'')
        key = key.replace('csv','')
        dataframe_collection[key] = pd.read_csv(file)
    return dataframe_collection

In [2]:
trip_data = path_to_dict(r'F:\Capstone Data\\')

In [3]:
for k,v in trip_data.items():
    k = re.findall('\d+',k)

In [4]:
key_list = []
df_list = []
for k,v in trip_data.items():
    v.columns = pd.Series(v.columns).str.lower()
    v.columns = pd.Series(v.columns).str.strip()
    v.columns = pd.Series(v.columns).str.replace(" ", "")
    v.loc[:, ['starttime', 'stoptime']] = pd.to_datetime(v.loc[:, ['starttime', 'stoptime']].stack(), 
    format='%Y-%m-%d %H:%M:%S', infer_datetime_format = True).unstack()
    key_list.append(k)
    df_list.append(v)

In [5]:
key_list = pd.Series(key_list).str.replace('\D+', '', regex = True)
key_list = key_list.str.slice(stop=4)

In [6]:
year_list = ['2013', '2014', '2015','2016','2017','2018','2019','2020']

In [7]:
dict_indexes = {}
for year in year_list:
    dict_indexes[year] = key_list[key_list == year].index.tolist()

In [8]:
df_list = pd.Series(df_list)

In [9]:
quik_2013 = pd.concat(df_list[dict_indexes['2013']].tolist())
quik_2014 = pd.concat(df_list[dict_indexes['2014']].tolist())
#quik_2015 = pd.concat(df_list[dict_indexes['2015']].tolist())
quik_2016 = pd.concat(df_list[dict_indexes['2016']].tolist())
quik_2017 = pd.concat(df_list[dict_indexes['2017']].tolist())
quik_2018 = pd.concat(df_list[dict_indexes['2018']].tolist())
quik_2019 = pd.concat(df_list[dict_indexes['2019']].tolist())
quik_2020 = pd.concat(df_list[dict_indexes['2020']].tolist())

In [10]:
quik_2016

,tripduration,starttime,stoptime,startstationid,startstationname,startstationlatitude,startstationlongitude,endstationid,endstationname,endstationlatitude,endstationlongitude,bikeid,usertype,birthyear,gender
0,1491,2016-03-01 06:52:42,2016-03-01 07:17:33,72,W 52 St & 11 Ave,40.767272,-73.993929,427,Bus Slip & State St,40.701907,-74.013942,23914,Subscriber,1982.0,1
1,1044,2016-03-01 07:05:50,2016-03-01 07:23:15,72,W 52 St & 11 Ave,40.767272,-73.993929,254,W 11 St & 6 Ave,40.735324,-73.998004,23697,Subscriber,1978.0,1
2,714,2016-03-01 07:15:05,2016-03-01 07:26:59,72,W 52 St & 11 Ave,40.767272,-73.993929,493,W 45 St & 6 Ave,40.756800,-73.982912,21447,Subscriber,1960.0,2
3,329,2016-03-01 07:26:04,2016-03-01 07:31:34,72,W 52 St & 11 Ave,40.767272,-73.993929,478,11 Ave & W 41 St,40.760301,-73.998842,22351,Subscriber,1986.0,1
4,1871,2016-03-01 07:31:30,2016-03-01 08:02:41,72,W 52 St & 11 Ave,40.767272,-73.993929,151,Cleveland Pl & Spring St,40.722104,-73.997249,20985,Subscriber,1978.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
919916,281,2016-03-31 17:23:09,2016-03-31 17:27:50,3246,Montague St & Clinton St,40.694281,-73.992300,2000,Front St & Washington St,40.702551,-73.989402,15275,Subscriber,1982.0,1
919917,248,2016-03-31 17:39:52,2016-03-31 17:44:00,3246,Montague St & Clinton St,40.694281,-73.992300,157,Henry St & Atlantic Ave,40.690893,-73.996123,19665,Subscriber,1973.0,1
919918,652,2016-03-31 19:52:14,2016-03-31 20:03:07,3246,Montague St & Clinton St,40.694281,-73.992300,467,Dean St & 4 Ave,40.683125,-73.978951,15230,Subscriber,1989.0,1
919919,1794,2016-03-31 20:40:46,2016-03-31 21:10:40,3246,Montague St & Clinton St,40.694281,-73.992300,3118,McGuinness Blvd & Eagle St,40.735550,-73.952840,19752,Subscriber,1975.0,1
919920,1188,2016-03-31 20:59:23,2016-03-31 21:19:11,3246,Montague St & Clinton St,40.694281,-73.992300,347,Greenwich St & W Houston St,40.728846,-74.008591,17288,Subscriber,1983.0,1