In [17]:
import pandas as pd
import numpy as np

In [22]:
ny_2013 = pd.read_csv('../data/weatherdata/ny_2013.csv')

/Users/danielchoy/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (44,53,86,87) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [41]:
pd.reset_option('display.max_columns', None)

In [ ]:
def clean_weatherdata(df):
    df = df[['DATE', 'STATION', 'SOURCE', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'NAME', 'WIND', 'TEMP',
             'DEW', 'SLP']]
    df['DATE'] = df['DATE'].str.replace('T', ' ')

In [33]:
ny_2013['DATE'] = ny_2013['DATE'].str.replace('T', ' ')

In [45]:
pd.set_option('display.max_columns', None)
ny_2013.head(5)

,STATION,DATE,SOURCE,LATITUDE,LONGITUDE,ELEVATION,NAME,REPORT_TYPE,CALL_SIGN,QUALITY_CONTROL,WND,CIG,VIS,TMP,DEW,SLP,AA1,AA2,AA3,AB1,AD1,AE1,AH1,AH2,AH3,AH4,AH5,AH6,AI1,AI2,AI3,AI4,AI5,AI6,AJ1,AK1,AM1,AN1,AT1,AT2,AT3,AT4,AT5,AT6,AT7,AU1,AU2,AU3,AU4,AW1,AW2,AW3,AW4,AW5,AX1,ED1,GA1,GA2,GA3,GA4,GA5,GA6,GD1,GD2,GD3,GD4,GF1,KA1,KA2,KB1,KB2,KB3,KC1,KC2,KD1,KD2,KE1,KG1,KG2,MA1,MD1,MF1,MG1,MH1,MK1,MW1,MW2,MW3,OC1,OD1,OE1,OE2,OE3,RH1,RH2,RH3,REM,EQD,Date
0,72503014732,2013-01-01 00:00:00,4,40.7792,-73.88,3.4,"LA GUARDIA AIRPORT, NY US",FM-12,KLGA,V020,"230,1,N,0077,1","99999,9,9,N","016000,1,N,1","+0033,1","-0072,1","10147,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"08,99,1,99,9,99,9,99999,9,99,9,99,9","120,M,+0039,1","180,N,-0005,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"99999,9,10135,1","8,1,006,1,+999,9",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYN098AAXX 01004 72503 32966 82315 10033 2107...,NaN,2013-01-01T00:00:00
1,72503014732,2013-01-01 00:51:00,7,40.7792,-73.88,3.4,"LA GUARDIA AIRPORT, NY US",FM-15,KLGA,V030,"240,5,N,0062,5","02286,5,M,N","016093,5,N,5","+0039,5","-0072,5","10137,5","01,0000,9,5",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"07,5,+02286,5,99,9","08,5,+03048,5,99,9",NaN,NaN,NaN,NaN,"3,99,1,+02286,5,9","4,99,1,+03048,5,9",NaN,NaN,"08,99,1,99,9,99,9,99999,9,99,9,99,9",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10139,5,10128,5",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"0103,5",NaN,NaN,NaN,NaN,NaN,NaN,NaN,MET10912/31/12 19:51:03 METAR KLGA 010051Z 240...,NaN,2013-01-01T00:51:00
2,72503014732,2013-01-01 01:51:00,7,40.7792,-73.88,3.4,"LA GUARDIA AIRPORT, NY US",FM-15,KLGA,V030,"240,5,N,0062,5","02743,5,M,N","016093,5,N,5","+0039,5","-0072,5","10126,5","01,0000,9,5",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"04,5,+02286,5,99,9","08,5,+02743,5,99,9",NaN,NaN,NaN,NaN,"2,99,1,+02286,5,9","4,99,1,+02743,5,9",NaN,NaN,"08,99,1,99,9,99,9,99999,9,99,9,99,9",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10125,5,10114,5",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"0088,5",NaN,NaN,NaN,NaN,NaN,NaN,NaN,MET10912/31/12 20:51:03 METAR KLGA 010151Z 240...,NaN,2013-01-01T01:51:00
3,72503014732,2013-01-01 02:51:00,7,40.7792,-73.88,3.4,"LA GUARDIA AIRPORT, NY US",FM-15,KLGA,V030,"240,5,N,0067,5","02591,5,M,N","016093,5,N,5","+0044,5","-0072,5","10120,5","01,0000,9,5",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"08,5,+02591,5,99,9",NaN,NaN,NaN,NaN,NaN,"4,99,1,+02591,5,9",NaN,NaN,NaN,"08,99,1,99,9,99,9,99999,9,99,9,99,9",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"10122,5,10111,5","6,9,026,9,+999,9",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"0113,5",NaN,NaN,NaN,NaN,NaN,NaN,NaN,MET10812/31/12 21:51:03 METAR KLGA 010251Z 240...,NaN,2013-01-01T02:51:00
4,72503014732,2013-01-01 03:00:00,4,40.7792,-73.88,3.4,"LA GUARDIA AIRPORT, NY US",FM-12,KLGA,V020,"240,1,N,0067,1","99999,9,9,N","016000,1,N,1","+0044,1","-0072,1","10120,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"08,99,1,99,9,99,9,99999,9,99,9,99,9",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"99999,9,10108,1","6,1,026,1,+999,9",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYN086AAXX 01034 72503 32966 82413 10044 2107...,NaN,2013-01-01T03:00:00